name: Build Anti-Deadzone Test

on:
  workflow_dispatch:

jobs:
  build_windows_avx2:
    name: Windows AVX2
    uses: ./.github/workflows/windows_build_qt.yml
    with:
      jobName: Anti-Deadzone Test
      artifactPrefixName: PCSX2-windows-Qt-x64-anti-deadzone
      configuration: Release AVX2
    secrets: inherit
